(deftheme horrocks
  "A minimal tty-first theme with semantic colors.")

(custom-theme-set-faces
 'horrocks
 '(button ((t (:inherit (link)))))
 '(cursor ((((type graphic))
            (:background "#0000ffffffff"))
           (((type tty) (min-colors 256))
            (:background "brightcyan"))))
 '(default ((((type graphic))
             (:background "#080808080808"
              :foreground "#6c6c6c6c6c6c"))
            (((type tty) (min-colors 256))
             (:background "grey5"
              :foreground "grey45"))))
 '(dired-directory ((((type graphic))
                     (:foreground "#00005f5f0000"))
                    (((type tty) (min-colors 256))
                     (:foreground "color-22"))))
 '(error ((default (:weight bold))
          (((type graphic))
           (:foreground "#ffff00000000"))
          (((type tty) (min-colors 256))
           (:foreground "brightred"))))
 '(font-lock-builtin-face ((((type graphic))
                            (:foreground "#00000000ffff"))
                           (((type tty) (min-colors 256))
                            (:foreground "color-21"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((((type graphic))
                            (:foreground "#00008787d7d7"))
                           (((type tty) (min-colors 256))
                            (:foreground "color-32"))))
 '(font-lock-constant-face ((t (:foreground "cyan"))))
 '(font-lock-doc-face ((((type graphic))
                        (:foreground "#0000afaf5f5f"))
                       (((type tty) (min-colors 256))
                        (:foreground "color-35"))))
 '(font-lock-function-name-face ((((type graphic))
                                  (:foreground "#00005f5f0000"))
                                 (((type tty) (min-colors 256))
                                  (:foreground "color-22"))))
 '(font-lock-keyword-face ((((type graphic))
                            (:foreground "#d7d7afaf0000"))
                           (((type tty) (min-colors 256))
                            (:foreground "color-178"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((((type graphic))
                                 (:foreground "#ffff5f5fffff"))
                                (((type tty) (min-colors 256))
                                 (:foreground "color-207"))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((((type graphic))
                           (:foreground "#d7d7afaf8787"))
                          (((type tty) (min-colors 256))
                           (:foreground "color-180"))))
 '(font-lock-type-face ((((type graphic))
                         (:foreground "#0000ffffd7d7"))
                        (((type tty) (min-colors 256))
                         (:foreground "color-50"))))
 '(font-lock-variable-name-face ((t (:foreground "lightyellow"))))
 '(font-lock-warning-face ((t (:inherit (error)))))
 '(fringe ((t (:inherit mode-line-inactive))))
 '(header-line ((t (:inherit (mode-line)))))
 '(highlight ((t (:background "grey20"))))
 '(isearch ((default (:foreground "black"))
            (((type graphic))
             (:background "#ffffffff0000"))
            (((type tty) (min-colors 256))
             (:background "brightyellow"))))
 '(isearch-fail ((t (:foreground "red"))))
 '(ivy-minibuffer-match-face-1 ((t (:inherit default))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit default))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit default))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit nil))))
 '(lazy-highlight ((t (:background "yellow" :foreground "black"))))
 '(link ((default (:underline t))
         (((type graphic))
          (:foreground "#87875f5fffff"))
         (((type tty) (min-colors 256))
          (:foreground "color-99"))))
 '(link-visited ((default (:inherit link))
                 (((type graphic))
                  (:foreground "#5f5f0000ffff"))
                 (((type tty) (min-colors 256))
                  (:foreground "color-57"))))
 '(match ((default (:foreground "black"))
          (((type graphic))
           (:background "#5f5fffff0000"))
          (((type tty) (min-colors 256))
           (:background "color-82"))))
 '(minibuffer-prompt ((t (:inherit default))))
 '(mode-line ((t (:background "grey10" :foreground "grey25"))))
 '(mode-line-buffer-id ((t nil)))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "black" :foreground "grey10"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(region ((((type graphic))
            (:background "#5f5f00000000"))
           (((type tty) (min-colors 256))
            (:background "color-52"))))
 '(shadow ((t (:foreground "grey20"))))
 '(show-paren-match ((default (:weight bold))
                     (((type graphic))
                      (:foreground "#5f5f0000ffff"))
                     (((type tty) (min-colors 256))
                      (:foreground "color-57"))))
 '(sp-pair-overlay-face ((t nil)))
 '(tooltip ((t (:foreground "black" :background "lightyellow"))))
 '(trailing-whitespace ((t (:background "white"))))
 '(whitespace-empty ((t (:background "ghostwhite"))))
 '(whitespace-line ((t (:background "grey8"))))
 '(whitespace-tab ((t (:foreground "tan"))))
 '(whitespace-trailing ((t (:inherit trailing-whitespace))))
 '(widget-field ((t
                  (:background "black"
                   :foreground "color-162"
                   :box (:line-width 2
                         :color "grey75"
                         :style pressed-button))))))

(provide-theme 'horrocks)
