(deftheme horrocks "A minimal tty-first theme with semantic colors.")

(defconst color--bubblegum "#ffff8787d7d7")
(defconst color--cerulean "#00008787d7d7")
(defconst color--dark-lilac "#5f5f0000ffff")
(defconst color--deep-red "#5f5f00000000")
(defconst color--dim-forest-green "#00005f5f0000")
(defconst color--key "#d7d7afaf0000")
(defconst color--lilac "#87875f5fffff")
(defconst color--dollar "#0000afaf5f5f")
(defconst color--pink "#ffff5f5fffff")
(defconst color--purple "#5f5f0000ffff")
(defconst color--serpentine "#8787d7d70000")
(defconst color--vanilla "lightyellow")

(custom-theme-set-faces
 'horrocks
 '(button ((t (:inherit (link)))))
 '(cursor ((t (:background "#0000ffffffff"))))
 '(default ((((type graphic))
             (:background "#080808080808"
              :foreground "#6c6c6c6c6c6c"))
            (((type tty) (min-colors 256))
             (:background "grey5"
              :foreground "grey45"))))
 '(diff-added ((t (:background "#335533" :foreground "black"))))
 ;; '(diff-changed ((t (:background "" :foreground ""))))
 '(diff-context ((t (:foreground "cornsilk"))))
 '(diff-file-header ((t (:background "grey60" :foreground "black"))))
 '(diff-function ((t (:inherit diff-header))))
 '(diff-header ((t (:background "grey45" :foreground "black"))))
 '(diff-hunk-header ((t (:inherit diff-header))))
 '(diff-index ((t (:inherit diff-file-header))))
 '(diff-indicator-added ((t (:inherit diff-added))))
 '(diff-indicator-changed ((t (:inherit diff-changed))))
 '(diff-indicator-removed ((t (:inherit diff-removed))))
 '(diff-nonexistent ((t (:inherit diff-file-header))))
 '(diff-refine-added ((t (:background "#22aa22" :foreground "black"))))
 '(diff-refine-changed ((t (:background "#aaaa22" :foreground "black"))))
 '(diff-refine-removed ((t (:background "#aa2222" :foreground "black"))))
 '(diff-removed ((t (:background "#553333" :foreground "black"))))
 `(dired-directory ((t (:foreground ,color--dim-forest-green))))
 '(error ((default (:weight bold))
          (((type graphic))
           (:foreground "#ffff00000000"))
          (((type tty) (min-colors 256))
           (:foreground "brightred"))))
 `(font-lock-builtin-face ((t (:foreground ,color--bubblegum))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 `(font-lock-comment-face ((t (:foreground ,color--cerulean))))
 '(font-lock-constant-face ((t (:foreground "cyan"))))
 `(font-lock-doc-face ((t (:foreground ,color--dollar))))
 '(font-lock-function-name-face ((t (:foreground "forestgreen"))))
 `(font-lock-keyword-face ((t (:foreground ,color--key))))
 '(font-lock-negation-char-face ((t nil)))
 `(font-lock-preprocessor-face ((t (:foreground ,color--pink))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "steelblue"))))
 '(font-lock-type-face ((t (:foreground "darkturquoise"))))
 `(font-lock-variable-name-face ((t (:foreground ,color--vanilla))))
 '(font-lock-warning-face ((t (:foreground "yellow" :weight bold))))
 '(fringe ((t (:inherit mode-line-inactive))))
 '(header-line ((t (:inherit (mode-line)))))
 '(highlight ((t (:background "grey20"))))
 '(isearch ((default (:foreground "black"))
            (((type graphic))
             (:background "#ffffffff0000"))
            (((type tty) (min-colors 256))
             (:background "brightyellow"))))
 '(isearch-fail ((t (:foreground "red"))))
 '(ivy-minibuffer-match-face-1 ((t (:inherit default))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit default))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit default))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit nil))))
 '(lazy-highlight ((t (:background "yellow" :foreground "black"))))
 `(link ((t (:foreground ,color--lilac :underline t))))
 `(link-visited ((t (:inherit link :foreground ,color--dark-lilac))))
 '(match ((default (:foreground "black"))
          (((type graphic))
           (:background "#5f5fffff0000"))
          (((type tty) (min-colors 256))
           (:background "color-82"))))
 '(minibuffer-prompt ((t (:inherit default))))
 '(mode-line ((t (:background "grey10" :foreground "grey25"))))
 '(mode-line-buffer-id ((t nil)))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:background "black" :foreground "grey10"))))
 '(next-error ((t (:inherit (region)))))
 '(org-block ((t (:inherit default))))
 '(query-replace ((t (:inherit (isearch)))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "grey20"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "grey30"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "grey40"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "grey50"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "grey60"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "grey70"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "grey80"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "grey90"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "grey100"))))
 '(rainbow-delimiters-mismatched-face ((t (:inherit error))))
 '(rainbow-delimiters-unmatched-face ((t (:inherit error))))
 `(region ((t (:background ,color--deep-red))))
 '(rcirc-other-nick ((t (:foreground "navajowhite"))))
 `(rcirc-server ((t (:foreground ,color--serpentine))))
 '(rcirc-timestamp ((t (:foreground "grey25"))))
 '(rcirc-url ((t (:inherit (link)))))
 '(shadow ((t (:foreground "grey20"))))
 `(show-paren-match ((t (:foreground ,color--purple :weight bold))))
 '(sp-pair-overlay-face ((t nil)))
 '(tooltip ((t (:foreground "black" :background "lightyellow"))))
 '(trailing-whitespace ((t (:background "white"))))
 '(whitespace-empty ((t (:background "ghostwhite"))))
 '(whitespace-line ((t (:background "grey8"))))
 '(whitespace-tab ((t (:foreground "tan"))))
 '(whitespace-trailing ((t (:inherit trailing-whitespace))))
 '(widget-field ((t
                  (:background "black"
                   :foreground "color-162"
                   :box (:line-width 2
                         :color "grey75"
                         :style pressed-button))))))

(provide-theme 'horrocks)
