(defun layout/2columns ()
  (interactive)
  (delete-other-windows)
  (split-window-horizontally)
  (balance-windows))

(defun layout/4squares ()
  (interactive)
  (layout/sandals)
  (balance-windows))

(defun layout/inverted-thong ()
  (interactive)
  (delete-other-windows)
  (split-window-vertically)
  (split-window-horizontally)
  (balance-windows)
  (enlarge-window 10))

(defun layout/fork ()
  (interactive)
  (delete-other-windows)
  (split-window-vertically)
  (split-window-horizontally)
  (split-window-horizontally)
  (select-window (window-in-direction 'below))
  (split-window-horizontally)
  (balance-windows-area)
  (shrink-window 6))

(defun layout/sandal ()
  (interactive)
  (delete-other-windows)
  (split-window-vertically)
  (balance-windows)
  (enlarge-window 10))

(defun layout/sandals ()
  (interactive)
  (delete-other-windows)
  (split-window-vertically)
  (split-window-horizontally)
  (select-window (window-in-direction 'below))
  (split-window-horizontally)
  (shrink-window 15))

(defun layout/thong ()
  (interactive)
  (delete-other-windows)
  (split-window-vertically)
  (select-window (window-in-direction 'below))
  (enlarge-window 15)
  (split-window-horizontally))
