(bind-key [remap list-buffers] 'ibuffer)
(bind-key [remap move-beginning-of-line] 'back-to-indentation*)
(bind-key "M-A" (lambda () (interactive) (activate-mark)))
(bind-key "<M-up>" (lambda () (interactive) (scroll-down (/ (window-height) 10))))
(bind-key "<M-down>" (lambda () (interactive) (scroll-up (/ (window-height) 10))))
(bind-key "<M-left>" (lambda () (interactive) (scroll-right (/ (window-width) 10))))
(bind-key "<M-right>" (lambda () (interactive) (scroll-left (/ (window-width) 10))))
(bind-key "<M-S-up>" (lambda () (interactive) (scroll-down 1)))
(bind-key "<M-S-down>" (lambda () (interactive) (scroll-up 1)))
(bind-key "<M-S-left>" (lambda () (interactive) (scroll-right 1)))
(bind-key "<M-S-right>" (lambda () (interactive) (scroll-left 1)))
(bind-key "<S-delete>" 'delete-region)
