(bind-key [remap list-buffers] 'ibuffer)
(bind-key [remap move-beginning-of-line] 'back-to-indentation*)
(bind-key "M-A" (lambda () (interactive) (activate-mark)))
(bind-key "<M-left>" 'scroll-right)
(bind-key "<M-right>" 'scroll-left)
(bind-key "<S-delete>" 'delete-region)
